name: Check Tests
on: push
jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: make install

      - name: Start tests
        run: make test
